### ISSUE TITLE
To-Do List & Update Notes

### ISSUE THREAD

**Issue by MK99MA** [MK99MA/SoMoE-19#1]
### OPEN / TO-DO  
- [ ] - Make overtime notifications toggleable per client
- [ ] - Add optional support for [Discord Integration](https://forums.alliedmods.net/showthread.php?t=292448)  
```
 - Send Notification at match end to bot
 - Allow players on server to sign up for a cap being started via discord
 - Allow the bot to "see" the server as being available
```
- [ ] - Auto-detect GK zones
- [ ] - "Bot-caps" Bots fighting the cap, randomly picking players based on their !pos (1 gk, 2 def, 1 mid, 2 wing)  
   - What if noone is available with the missing pos?
   - What about the last picks?
- [ ] - discord Integration? (Send Cap notifications /Match results? )
- [ ] - CS:GO support (see [CS:GO Quirks](https://wiki.alliedmods.net/CSGO_Quirks))
- [ ] - Translation support
- [ ] - Clean up / Optimization

### DONE
- [x] - Add command to manually use a random password [[See here](https://github.com/MK99MA/soccermod-2019edit/issues/1#issuecomment-531322535)]
- [x] - Add command to set default serverpw [[See here](https://github.com/MK99MA/soccermod-2019edit/issues/1#issuecomment-531322535)]
- [x] - Get default pw from server.cfg instead of only using the previous one [[See here](https://github.com/MK99MA/soccermod-2019edit/issues/1#issuecomment-531509121)]
- [x] - Add trainingball model to archive
- [x] - Floodcheck exception [[See here](https://github.com/MK99MA/soccermod-2019edit/issues/1#issuecomment-527424060)]
- [x] - Autokick AFK  if lockset enabled AND cap started [[See here](https://github.com/MK99MA/soccermod-2019edit/issues/1#issuecomment-528985554)]
- [x] - Fix ClanTag for teamname[[See here](https://github.com/MK99MA/soccermod-2019edit/issues/1#issuecomment-531322535)]
- [x] - Score overview & Cards in matchlog [[See here](https://github.com/MK99MA/soccermod-2019edit/issues/1#issuecomment-531322535)]
- [x] - Fix Breaklength not saving from the menu [[See here](https://github.com/MK99MA/soccermod-2019edit/issues/1#issuecomment-531322535)]
- [x] - Rewrite Sourcemod Admin Functions (admins.cfg instead of admin_simple.ini -> remove sourcemod admin) [[See here](https://github.com/MK99MA/soccermod-2019edit/issues/1#issuecomment-531509121)]
- [x] - Position Display in PickMenu showing only for 1st in list - **FIXED**
- [x] - Updater
> - OPTIONAL BUT HIGHLY RECOMMENDED
> - REQUIRES ADDITIONAL FILES, SEE [HERE](https://github.com/MK99MA/soccermod-2019edit/blob/master/README.md#installation)

- [x] - FIXED: Admin Onlinelist bugged
- [x] - FIXED: Menu closing when attempting to open empty simple_admin list 
- [x] - CHANGED: Reworked admins.cfg generation
```
 - Creates a Backup of the original admins.cfg named admins.cfg.presoccermod
 - Should ignore the comments in the default file and only copy the actual admins to the new file
 - In case something goes wrong (File does not start with "Admins") it will rename it to admins.cfg.error and create a new, empty admins.cfg
 - NOTICE: Writing to a File is somewhat limited.. If you got too many Admins in the File, and therefore alot of lines to WRITE not every line might be copied, thus leaving the admins.cfg file incomplete. There is no check for this case!
```
 - [x] - 'WORKAROUND' ~~CD Bar mismatching~~ Armor Counter added - See below
 - [x] - ADDED: Toggle-able (in Sprintinfo menu) Armor Counter added:
```
- De- and Increases relative to sprint-length and cooldown (in steps of 5; might change it, needs testing)
- Ignores damage by the ball, so should be always "accurate"
- CHANGED: Starting a cap match will deactivate sprint now, as well as setting the Armor to 0
```
- [x] ADDED: Forfeit Vote 
```
- command (!forfeit) usable if Team X is Y(var) goals in front
- Involves only the 12 playing players - NO SPECS
- Requires ~66,6% (2/3) of GIVEN votes to succeed
- Configurable: Enable/Disable, number of req goals, startable by admin / everyone, auto-spec after a successful vote on/off, "cap mode" on/off
- Cap Mode: After a successful Capfight round the following match will have the command enabled, else it will be disabled (maprr DOES NOT reset it)
-  Autodisable if no match was started X minutes after a cap
-  Additional Timer to keep the ForfeitVote enabled if a match is restarted within 120 seconds
-  Keep it enabled if a match gets restarted for whatever reason
```
- [x] - ADDED: Matchsettings info when starting a Match ( Toggleable)
- [x] - ADDED: Sounds (Previous: Halftime whistle / Center message)
- [x] - FIXED: 'Remove Red Card' menu - ADDED: 'Remove Yellow Card' menu  
- [x] - CHANGED: location for the file storing cards  
- [x] - ADDED: ReadyCheck when paused (Auto & Manual mode) Auto mode switches to manual mode after 5 minutes as a workaround to potential scenarios in which the Auto unpause won't work  
- [x] - CHANGED: Colorpreview menu remembers the position  
- [x] - ADDED: !cancel command to exit any chat input  
- [x] - FIXED: Clantag Nameset
- [x] - ADDED: personal cannon
- [x] - FIXED: fix "catapult" issue with ball cannon
- [x] - AFK Kick Immunity Options 
- [x] - "Spec only"-Position in position-menu  
- [x] - !lc command with configurable rr tolerance  
- [x] - customizable map defaults     

### SCRAPPED (for now)
- [ ] - ~~Improvements to AFK Kick (Timer starting after last movement)~~
- [ ] - ~~Timer with configurable time to reset lockset (?)~~
- [ ] - ~~additional ways to remove serverlock state (?)~~ 
- [ ] - ~~Matchlog parse current score before adding new score -> Preventing issues with removed goals?~~

**Comment by MK99MA** [comment]
Commit 03.09.2019
"Floodcheck exception"
instead of trying to change the cvar the plugin will move antiflood.smx to the disabled folder
DOES NOT REVERT IT ITSELF WHEN UNLOADED.

**Comment by MK99MA** [comment]
Commit 06.09.2019
"Autokick AFK if lockset enabled AND cap started"
If both conditions are true, after x seconds of being AFK (configurable with console command or in the lockset menu) a randomized menu will ask the AFK player for input. 
If the AFK player doesn't respond with the right action OR within y seconds (configurable like above) he will be kicked after x + y seconds. 
Succeeding the check will only reset the timer.
If soccer_mod.cfg already exists the default values won't be added until an user changes them ingame.

**Comment by MK99MA** [comment]
Commit 13.09.2019 BETA11
Fixes:
- Tag for Teamname should work better now
- Dead & Respawning players should be frozen during a pause now
- Fixed break length setting in menu saving and reading a wrong value
- Fixed break length setting chat message
- minor chat message fixes

Additions:
- matchlog will track given cards (added to the end of the matchlog menu)
- overview of the matchstats (goals, assists, owngoals, namechanges) added to the matchlog textfile
- !rpass - manually set a random pw
- !dpass - manually reset the pw if it was randomized

Improvements:
- improved randomness of generated pw string
- improved AFK Kick during Serverlock(WIP)

**Comment by MK99MA** [comment]
Commit 21.09.2019 BETA12
Fixes:
- AFK Kick Timer getting terminated correctly (hopefully finally for good..)
- some more fixes about terminating the timers...
- Default pw will now be stored from server.cfg instead of saving the current one as "default"
- minor chat message fixes

Changes:
- Set default afk timer to 100 seconds, captcha menu to 20 seconds (previously 120 + 30)
- Add soccer tags to servers if plugin is loaded (soccer,soccermod,soccer_mod)
- Revamped Add admin options (admins.cfg + admins_simple.ini; remove & edit sourcemod admins ingame etc)

**Comment by MK99MA** [comment]
Commit 24.09.2019 BETA13
Fixes:
- fixed removing of Soccer Mod admins

Changes:
- several text changes / fixes
